repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^(index\.html|feed\.xml|sitemap\.xml)$
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        args: [--strict, --ignore-missing-imports]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [html, css, javascript, json, yaml, markdown]
        exclude: ^(feed\.xml|sitemap\.xml|index\.html)$

  - repo: local
    hooks:
      - id: validate-posts
        name: Validate blog posts
        entry: python scripts/validate.py
        language: system
        files: ^posts/.*\.(json|html)$
        pass_filenames: false

      - id: build-site
        name: Build site files
        entry: python scripts/build_index.py
        language: system
        files: ^posts/.*\.(json|html)$
        pass_filenames: false
