name: Build site
on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install dependencies
        run: pip install -e ".[dev]"
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1

  build:
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build site
        run: python scripts/build_index.py
      - name: Commit generated files
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add index.html feed.xml sitemap.xml
            git commit -m "chore: rebuild index/feed/sitemap"
            git push
          fi
